# Generated by Django 6.1.1 on 2026-09-07 13:37

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0014_club_background_video'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Titulo')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Subtitulo')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='Slug (URL)')),
                ('author', models.CharField(blank=True, help_text='Ex: Redacao AllCourts365 ou Redacao Clube 22 de Agosto', max_length=200, verbose_name='Escrito por')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Conteudo da Noticia')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/', verbose_name='Imagem de Destaque')),
                ('video', models.FileField(blank=True, null=True, upload_to='news/videos/', verbose_name='Video de Destaque')),
                ('media_credit', models.CharField(blank=True, help_text='Ex: Foto: Joao Silva | Arquivo do clube', max_length=400, verbose_name='Credito / Legenda da Midia')),
                ('is_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Publicacao')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('club', models.ForeignKey(blank=True, help_text='Deixe em branco para publicar na home do AllCourts365', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='clubs.club', verbose_name='Clube / Liga')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
