# Generated by Django 6.1.1 on 2026-09-07 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_club_background_video'),
        ('news', '0002_news_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_global',
            field=models.BooleanField(default=False, help_text='Marque para veicular esta noticia na home global.', verbose_name='Home do AllCourts365'),
        ),
        migrations.AlterField(
            model_name='news',
            name='club',
            field=models.ForeignKey(blank=True, help_text='Clube ou liga a qual a noticia pertence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='clubs.club', verbose_name='Clube / Liga'),
        ),
    ]
