# Generated by Django 6.1.1 on 2026-09-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_is_global_alter_news_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='anonymous_likes',
            field=models.PositiveIntegerField(default=0, verbose_name='Curtidas Anonimas'),
        ),
    ]
