# Generated by Django 6.1.1 on 2026-09-10 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_club_is_visible'),
        ('news', '0004_news_anonymous_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Comunicação', 'verbose_name_plural': 'Comunicações'},
        ),
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Assunto')),
                ('body', models.TextField(verbose_name='Mensagem')),
                ('is_global', models.BooleanField(default=False, verbose_name='Mensagem Global (Todos os Usuários)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Clube/Liga')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente')),
            ],
            options={
                'verbose_name': 'Comunicado (Broadcast)',
                'verbose_name_plural': 'Comunicados (Broadcast)',
                'ordering': ['-created_at'],
            },
        ),
    ]
