# Generated by Django 6.1.1 on 2026-09-11 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_options_broadcastmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
    ]
