# Generated by Django 6.1.1 on 2026-09-20 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_club_has_departments_department_player_department_and_more'),
        ('news', '0006_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='broadcastmessage',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Selecione o departamento se aplicável.', null=True, on_delete=django.db.models.deletion.CASCADE, to='clubs.department', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='news',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Selecione o departamento caso o clube possua departamentos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='clubs.department', verbose_name='Departamento'),
        ),
    ]
