# Generated by Django 5.1.1 on 2026-09-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name='Imagem de Fundo')),
                ('watermark_image', models.ImageField(blank=True, null=True, upload_to='site_config/', verbose_name="Marca d'Água")),
                ('background_color', models.CharField(default='#0f172a', max_length=7, verbose_name='Cor de Fundo Fixa')),
                ('overlay_color', models.CharField(default='#000000', max_length=7, verbose_name='Cor do Fumê (Overlay)')),
                ('overlay_opacity', models.FloatField(default=0.5, help_text='0 = Transparente, 1 = Sólido', verbose_name='Opacidade do Fumê (0.0 a 1.0)')),
                ('highlight_color', models.CharField(default='#3b82f6', max_length=7, verbose_name='Cor de Destaque (Botões, Links)')),
                ('title_color', models.CharField(default='#ffffff', max_length=7, verbose_name='Cor do Título Principal')),
                ('subtitle_color', models.CharField(default='#94a3b8', max_length=7, verbose_name='Cor do Subtítulo')),
                ('watermark_position', models.CharField(choices=[('top-left', 'Superior Esquerdo'), ('top-right', 'Superior Direito'), ('bottom-left', 'Inferior Esquerdo'), ('bottom-right', 'Inferior Direito'), ('center', 'Centro')], default='bottom-left', max_length=20, verbose_name="Posição da Marca d'Água")),
                ('watermark_opacity', models.FloatField(default=0.8, verbose_name="Opacidade da Marca d'Água (0.0 a 1.0)")),
                ('watermark_size_percent', models.IntegerField(default=15, help_text='Porcentagem em relação à tela', verbose_name="Tamanho da Marca d'Água (%)")),
            ],
            options={
                'verbose_name': 'Configuração do Site',
                'verbose_name_plural': 'Configuração do Site',
            },
        ),
    ]
