# Generated by Django 6.1 on 2026-09-04 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_player_user'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLinkRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado')], default='pending', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolvido em')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.club', verbose_name='Clube')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.player', verbose_name='Atleta Desejado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='link_requests', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Requerente')),
            ],
            options={
                'verbose_name': 'Solicitação de Vínculo de Atleta',
                'verbose_name_plural': 'Solicitações de Vínculo de Atleta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='Nome Completo')),
                ('racket', models.CharField(blank=True, max_length=100, verbose_name='Raquete que usa')),
                ('handedness', models.CharField(blank=True, choices=[('D', 'Destro'), ('C', 'Canhoto')], max_length=50, verbose_name='Empunhadura')),
                ('backhand', models.CharField(blank=True, choices=[('1', 'Uma Mão'), ('2', 'Duas Mãos')], max_length=50, verbose_name='Backhand')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
