# Generated by Django 6.1.1 on 2026-09-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playerlinkrequest_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='handedness',
            field=models.CharField(blank=True, choices=[('D', 'Destro'), ('C', 'Canhoto'), ('A', 'Ambidestro')], max_length=50, verbose_name='Empunhadura'),
        ),
    ]
