# Generated by Django 6.1 on 2026-09-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_facebook',
            field=models.URLField(blank=True, verbose_name='Link do Facebook'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_instagram',
            field=models.URLField(blank=True, verbose_name='Link do Instagram'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_show',
            field=models.BooleanField(default=True, verbose_name='Exibir Rodapé (Footer)'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_text',
            field=models.TextField(blank=True, verbose_name='Texto/Copyright do Rodapé'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_whatsapp',
            field=models.URLField(blank=True, verbose_name='Link do WhatsApp'),
        ),
    ]
