# Generated by Django 6.1 on 2026-09-05 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_siteconfiguration_footer_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='footer_whatsapp',
            field=models.CharField(blank=True, help_text='Apenas números, com DDD (ex: 5511999999999)', max_length=50, verbose_name='Número do WhatsApp'),
        ),
    ]
