# Generated by Django 6.1 on 2026-09-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_siteconfiguration_footer_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_width',
            field=models.CharField(default='100%', help_text='Ex: 100%, 1200px, 80vw', max_length=20, verbose_name='Largura do Rodapé'),
        ),
    ]
