# Generated by Django 6.1 on 2026-09-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_siteconfiguration_footer_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_padding',
            field=models.CharField(default='40px 20px', help_text='Ex: 40px 20px (40px em cima/baixo, 20px nas laterais) ou 10px', max_length=20, verbose_name='Espessura (Padding) do Rodapé'),
        ),
    ]
