# Generated by Django 6.1.1 on 2026-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_siteconfiguration_footer_padding'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='background_video',
            field=models.FileField(blank=True, help_text='Se preenchido, o vídeo sobrescreve a imagem de fundo. Use arquivos .mp4 ou .webm.', null=True, upload_to='site_config/videos/', verbose_name='Vídeo de Fundo'),
        ),
    ]
