# Generated by Django 6.1.1 on 2026-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_siteconfiguration_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_analytics_id',
            field=models.CharField(blank=True, help_text='Ex: G-XXXXXXXXXX', max_length=50, null=True, verbose_name='ID de Medição do Google Analytics'),
        ),
    ]
