# Generated by Django 6.1.1 on 2026-09-08 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_siteconfiguration_google_analytics_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Responsável')),
                ('club_name', models.CharField(max_length=200, verbose_name='Nome do Clube/Liga')),
                ('phone', models.CharField(max_length=50, verbose_name='WhatsApp/Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail (Opcional)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Solicitação')),
                ('contacted', models.BooleanField(default=False, verbose_name='Contato Realizado?')),
            ],
            options={
                'verbose_name': 'Interesse de Clube (Lead)',
                'verbose_name_plural': 'Interesses de Clubes (Leads)',
                'ordering': ['-created_at'],
            },
        ),
    ]
