# Generated by Django 6.1.1 on 2026-09-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clublead'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='show_clubs_cta',
            field=models.BooleanField(default=True, help_text='Se desmarcado, a opção de prospectar novos clubes não aparecerá no topo do site.', verbose_name="Exibir botão 'Para Clubes' no menu"),
        ),
    ]
