# Generated by Django 6.1.1 on 2026-09-11 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_siteconfiguration_show_clubs_cta'),
        ('news', '0006_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='broadcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivered_messages', to='news.broadcastmessage', verbose_name='Comunicado Origem'),
        ),
    ]
