# Generated by Django 6.1.1 on 2026-09-17 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_message_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='avatar1.png', max_length=100, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='best_shot',
            field=models.CharField(blank=True, max_length=100, verbose_name='Melhor Golpe'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cidade / Endereço'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='WhatsApp / Telefone'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='play_style',
            field=models.CharField(blank=True, max_length=100, verbose_name='Estilo de Jogo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_time',
            field=models.CharField(blank=True, max_length=100, verbose_name='Horários Preferidos para Jogar'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='shirt_size',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG'), ('XG', 'XG')], max_length=5, verbose_name='Tamanho da Camiseta'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='string_tension',
            field=models.CharField(blank=True, help_text='Ex: 48 lbs, 50/52', max_length=50, verbose_name='Tensão da Corda (Libras)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='string_type',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tipo de Corda Favorita'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tennis_idol',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ídolo no Tênis'),
        ),
    ]
