# Generated by Django 6.1.1 on 2026-09-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_userprofile_address_userprofile_cep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Avatar'),
        ),
    ]
