# Generated by Django 6.1.1 on 2026-09-20 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(help_text='Ex: https://instagram.com/meuclube ou https://wa.me/5511999999999', max_length=500, verbose_name='URL / Endereço')),
                ('label', models.CharField(blank=True, help_text='Texto opcional que aparece ao lado do ícone. Deixe em branco para exibir só o ícone.', max_length=100, verbose_name='Rótulo (opcional)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordem de exibição')),
                ('site_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_links', to='core.siteconfiguration', verbose_name='Configuração do Site')),
            ],
            options={
                'verbose_name': 'Link do Rodapé',
                'verbose_name_plural': 'Links do Rodapé',
                'ordering': ['order', 'id'],
            },
        ),
    ]
