# Generated by Django 6.1.1 on 2026-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_footer_link_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='club_cta_text',
            field=models.TextField(default='Automatize a gestão de Torneios, Rankings e Agendamento de Quadras. Ofereça uma experiência premium para seus atletas enquanto você economiza horas de trabalho no WhatsApp e planilhas.', verbose_name='Texto do Card Para Clubes'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='club_cta_title',
            field=models.CharField(default='Eleve o nível do seu Clube', max_length=100, verbose_name='Título do Card Para Clubes'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='club_cta_whatsapp',
            field=models.CharField(default='5516997063560', help_text='Apenas números, com DDD (ex: 5516997063560)', max_length=50, verbose_name='WhatsApp para Vendas (Card Clubes)'),
        ),
    ]
