# Generated by Django 6.1.1 on 2026-09-23 15:30

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clubs', '0040_add_allow_visitors_to_club'),
        ('core', '0019_siteconfiguration_club_cta_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalLogin',
            fields=[
            ],
            options={
                'verbose_name': 'Conta de Acesso (Senha)',
                'verbose_name_plural': 'Contas de Acesso (Senhas)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioPorClube',
            fields=[
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clubs.player',),
        ),
    ]
