# Generated by Django 6.1.1 on 2026-09-23 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_globallogin_usuarioporclube'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPorClube',
        ),
        migrations.AlterModelOptions(
            name='globallogin',
            options={'verbose_name': 'Usuário', 'verbose_name_plural': 'Usuários'},
        ),
    ]
