# Generated by Django 6.1.1 on 2026-09-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_delete_usuarioporclube_alter_globallogin_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Aceite'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Aceite'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Termos Aceitos'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='terms_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Versão dos Termos'),
        ),
    ]
