# Generated by Django 6.1.1 on 2026-10-01 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_userprofile_consent_date_userprofile_consent_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='use_modern_admin',
            field=models.BooleanField(default=True, verbose_name='Usar Painel Moderno'),
        ),
    ]
