# Generated by Django 6.1.1 on 2026-10-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_userprofile_use_modern_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminThemeSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('default', 'Default (Claro)'), ('cerulean', 'Cerulean (Azul Clássico)'), ('cosmo', 'Cosmo (Moderno e Limpo)'), ('flatly', 'Flatly (Plano e Elegante)'), ('journal', 'Journal (Estilo Caderno)'), ('litera', 'Litera (Tipografia Leve)'), ('lumen', 'Lumen (Claro com Sombras)'), ('lux', 'Lux (Chique e Minimalista)'), ('materia', 'Materia (Material Design Claro)'), ('minty', 'Minty (Verde Claro)'), ('pulse', 'Pulse (Roxo Suave)'), ('sandstone', 'Sandstone (Areia)'), ('simplex', 'Simplex (Minimalista Vermelho)'), ('spacelab', 'Spacelab (Cores Sólidas)'), ('united', 'United (Laranja)'), ('yeti', 'Yeti (Azul Gelo)'), ('zephyr', 'Zephyr (Brisa Leve)'), ('darkly', 'Darkly (Escuro Padrão)'), ('cyborg', 'Cyborg (Preto Puro e Azul)'), ('slate', 'Slate (Cinza Escuro e Neutro)'), ('solar', 'Solar (Esverdeado Escuro)'), ('superhero', 'Superhero (Azul Escuro Intenso)'), ('vapor', 'Vapor (Neon Retrô)')], default='darkly', max_length=50, verbose_name='Tema do Painel')),
                ('is_dark', models.BooleanField(default=True, help_text='Marque isso se o tema for escuro para ajustar os menus laterais.', verbose_name='É um tema escuro?')),
            ],
            options={
                'verbose_name': 'Configuração do Tema do Painel',
                'verbose_name_plural': 'Configurações do Tema do Painel',
            },
        ),
    ]
