# Generated by Django 5.1.1 on 2026-09-03 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Categoria')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Encerrada')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Clube')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clubs/logos/', verbose_name='Logotipo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('address', models.CharField(blank=True, max_length=300, verbose_name='Endereço')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Clube',
                'verbose_name_plural': 'Clubes',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Atleta')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.club', verbose_name='Clube')),
            ],
            options={
                'verbose_name': 'Atleta',
                'verbose_name_plural': 'Atletas',
                'unique_together': {('club', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Torneio/Ranking')),
                ('tournament_type', models.CharField(choices=[('ranking', 'Ranking Contínuo'), ('knockout', 'Torneio Eliminatório')], default='ranking', max_length=20, verbose_name='Tipo')),
                ('competition_type', models.CharField(choices=[('simples', 'Simples'), ('duplas', 'Duplas')], default='simples', max_length=20, verbose_name='Competição')),
                ('set_format', models.CharField(choices=[('3_normal', 'Melhor de 3 Sets Normal'), ('3_super', 'Melhor de 3 Sets (3º Set é Super Tiebreak)'), ('5_normal', 'Melhor de 5 Sets Normal')], default='3_normal', max_length=20, verbose_name='Formato de Sets')),
                ('current_round', models.IntegerField(default=1, verbose_name='Rodada Atual')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('number_of_brackets', models.IntegerField(default=1, verbose_name='Número de Chaves (Eliminatório)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo (Exibir no site)')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Encerrado')),
                ('points_winner_2x0', models.IntegerField(default=3, verbose_name='Pontos (Vitória 2x0)')),
                ('points_winner_2x1', models.IntegerField(default=2, verbose_name='Pontos (Vitória 2x1)')),
                ('points_loser_2x1', models.IntegerField(default=1, verbose_name='Pontos (Derrota 2x1)')),
                ('points_loser_2x0', models.IntegerField(default=0, verbose_name='Pontos (Derrota 2x0)')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='clubs.club', verbose_name='Clube')),
            ],
            options={
                'verbose_name': 'Torneio/Ranking Base',
                'verbose_name_plural': 'Torneios/Rankings Base',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField(verbose_name='Rodada')),
                ('sets_a', models.IntegerField(blank=True, null=True, verbose_name='Sets Ganhos (A)')),
                ('sets_b', models.IntegerField(blank=True, null=True, verbose_name='Sets Ganhos (B)')),
                ('phase', models.CharField(blank=True, max_length=50, verbose_name='Fase')),
                ('position_in_bracket', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Finalizado'), ('cancelled', 'Não Ocorreu (Cancelado)')], default='pending', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='clubs.category')),
                ('next_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_matches', to='clubs.match')),
                ('player_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_a', to='clubs.player')),
                ('player_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_b', to='clubs.player')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='clubs.player')),
                ('tournament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_matches', to='clubs.tournament')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='clubs.tournament'),
        ),
        migrations.CreateModel(
            name='KnockoutTournament',
            fields=[
            ],
            options={
                'verbose_name': 'Torneio Eliminatório',
                'verbose_name_plural': 'Torneios Eliminatórios',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clubs.tournament',),
        ),
        migrations.CreateModel(
            name='RankingTournament',
            fields=[
            ],
            options={
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('clubs.tournament',),
        ),
        migrations.CreateModel(
            name='CategoryPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Pontos')),
                ('matches_played', models.IntegerField(default=0, verbose_name='Jogos')),
                ('wins', models.IntegerField(default=0, verbose_name='Vitórias')),
                ('losses', models.IntegerField(default=0, verbose_name='Derrotas')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='clubs.category')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clubs.player')),
            ],
            options={
                'verbose_name': 'Classificação',
                'verbose_name_plural': 'Classificações',
                'ordering': ['-points', '-wins', 'matches_played'],
                'unique_together': {('category', 'player')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('tournament', 'name')},
        ),
    ]
