# Generated by Django 5.1.1 on 2026-09-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='background_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Fundo Fixa (Hex)'),
        ),
        migrations.AddField(
            model_name='club',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/backgrounds/', verbose_name='Imagem de Fundo'),
        ),
        migrations.AddField(
            model_name='club',
            name='highlight_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor de Destaque'),
        ),
        migrations.AddField(
            model_name='club',
            name='overlay_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor do Fumê (Overlay)'),
        ),
        migrations.AddField(
            model_name='club',
            name='overlay_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name='Opacidade do Fumê (0.0 a 1.0)'),
        ),
        migrations.AddField(
            model_name='club',
            name='subtitle_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor do Subtítulo'),
        ),
        migrations.AddField(
            model_name='club',
            name='title_color',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='Cor do Título Principal'),
        ),
        migrations.AddField(
            model_name='club',
            name='watermark_image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/watermarks/', verbose_name="Marca d'Água do Clube"),
        ),
        migrations.AddField(
            model_name='club',
            name='watermark_opacity',
            field=models.FloatField(blank=True, null=True, verbose_name="Opacidade da Marca d'Água"),
        ),
        migrations.AddField(
            model_name='club',
            name='watermark_position',
            field=models.CharField(blank=True, choices=[('top-left', 'Superior Esquerdo'), ('top-right', 'Superior Direito'), ('bottom-left', 'Inferior Esquerdo'), ('bottom-right', 'Inferior Direito'), ('center', 'Centro')], max_length=20, null=True, verbose_name="Posição da Marca d'Água"),
        ),
        migrations.AddField(
            model_name='club',
            name='watermark_size_percent',
            field=models.IntegerField(blank=True, null=True, verbose_name="Tamanho da Marca d'Água (%)"),
        ),
    ]
