# Generated by Django 5.1.1 on 2026-09-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_background_color_club_background_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Site do Clube'),
        ),
    ]
