# Generated by Django 5.1.1 on 2026-09-03 17:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_club_website'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='administrators',
            field=models.ManyToManyField(blank=True, related_name='managed_clubs', to=settings.AUTH_USER_MODEL, verbose_name='Administradores'),
        ),
    ]
