# Generated by Django 5.1.1 on 2026-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_club_administrators'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='set1_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 1 (A)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set1_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 1 (B)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 2 (A)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set2_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 2 (B)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 3 (A)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set3_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 3 (B)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set4_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 4 (A)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set4_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 4 (B)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set5_a',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 5 (A)'),
        ),
        migrations.AddField(
            model_name='match',
            name='set5_b',
            field=models.IntegerField(blank=True, null=True, verbose_name='Set 5 (B)'),
        ),
    ]
