# Generated by Django 6.1 on 2026-09-04 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='saturday_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Fechamento (Sábados)'),
        ),
        migrations.AddField(
            model_name='club',
            name='saturday_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Abertura (Sábados)'),
        ),
        migrations.AddField(
            model_name='club',
            name='sunday_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Fechamento (Domingos/Feriados)'),
        ),
        migrations.AddField(
            model_name='club',
            name='sunday_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Abertura (Domingos/Feriados)'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekday_close',
            field=models.TimeField(blank=True, null=True, verbose_name='Fechamento (Dias de Semana)'),
        ),
        migrations.AddField(
            model_name='club',
            name='weekday_open',
            field=models.TimeField(blank=True, null=True, verbose_name='Abertura (Dias de Semana)'),
        ),
        migrations.AddField(
            model_name='match',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data e Hora Agendada'),
        ),
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Quadra')),
                ('is_ranking_court', models.BooleanField(default=False, verbose_name='Usada para Jogos de Ranking?')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='clubs.club', verbose_name='Clube')),
            ],
            options={
                'verbose_name': 'Quadra',
                'verbose_name_plural': 'Quadras',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='clubs.court', verbose_name='Quadra Reservada'),
        ),
    ]
