# Generated by Django 6.1 on 2026-09-04 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0008_match_proposed_result_json_match_reported_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_schedules', to='clubs.player'),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_court',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_matches', to='clubs.court'),
        ),
        migrations.AddField(
            model_name='match',
            name='proposed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='schedule_status',
            field=models.CharField(choices=[('unagendado', 'Não Agendado'), ('aguardando_adversario', 'Aguardando Adversário'), ('agendado', 'Agendado')], default='unagendado', max_length=30),
        ),
    ]
