# Generated by Django 6.1.1 on 2026-09-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_match_proposed_by_match_proposed_court_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryplayer',
            name='is_seed',
            field=models.BooleanField(default=False, verbose_name='Cabeça de Chave'),
        ),
        migrations.AddField(
            model_name='categoryplayer',
            name='seed_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Cabeça de Chave'),
        ),
        migrations.AddField(
            model_name='match',
            name='is_bye',
            field=models.BooleanField(default=False, verbose_name='Jogo BYE (Avanço Automático)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_campeon',
            field=models.IntegerField(blank=True, null=True, verbose_name='Campeão — Pts Extras'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_final_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final — Pts por Participação (Vice)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_final_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Final — Pts por Vitória (Campeão)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_oitavas_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oitavas — Pts por Participação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_oitavas_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oitavas — Pts por Vitória'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_quartas_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quartas — Pts por Participação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_quartas_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quartas — Pts por Vitória'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_round16_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round 16 — Pts por Participação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_round16_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round 16 — Pts por Vitória'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_round32_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round 32 — Pts por Participação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_round32_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round 32 — Pts por Vitória'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_round64_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round 64 — Pts por Participação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_round64_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Round 64 — Pts por Vitória'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_semi_participant',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semifinal — Pts por Participação'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pts_semi_winner',
            field=models.IntegerField(blank=True, null=True, verbose_name='Semifinal — Pts por Vitória'),
        ),
    ]
