# Generated by Django 6.1.1 on 2026-09-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_categoryplayer_is_seed_categoryplayer_seed_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='points_loser_2x0',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Pontos (Derrota 2x0)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='points_loser_2x1',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Pontos (Derrota 2x1)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='points_winner_2x0',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Pontos (Vitória 2x0)'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='points_winner_2x1',
            field=models.IntegerField(blank=True, default=2, null=True, verbose_name='Pontos (Vitória 2x1)'),
        ),
    ]
