# Generated by Django 6.1 on 2026-09-05 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_make_scoring_fields_optional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryplayer',
            options={'ordering': ['-points', '-wins', 'matches_played'], 'verbose_name': 'Inscrição na Competição', 'verbose_name_plural': 'Inscrições nas Competições'},
        ),
        migrations.AlterModelOptions(
            name='club',
            options={'verbose_name': 'Clube / Liga', 'verbose_name_plural': 'Clubes / Ligas'},
        ),
        migrations.AlterField(
            model_name='player',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='player_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Usuário do Sistema'),
        ),
    ]
