# Generated by Django 6.1.1 on 2026-09-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0013_tournament_allow_player_results_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='background_video',
            field=models.FileField(blank=True, help_text='Se preenchido, sobrescreve a imagem de fundo. Use .mp4 ou .webm.', null=True, upload_to='clubs/videos/', verbose_name='Vídeo de Fundo'),
        ),
    ]
