# Generated by Django 6.1.1 on 2026-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0014_club_background_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='rules_pdf',
            field=models.FileField(blank=True, help_text='Upload do regulamento do clube em formato PDF.', null=True, upload_to='clubs/rules/', verbose_name='Regulamento (PDF)'),
        ),
    ]
