# Generated by Django 6.1.1 on 2026-09-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0015_club_rules_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Imagem que aparece na guia do navegador (recomendado: 32x32 ou 64x64)', null=True, upload_to='clubs/favicons/', verbose_name='Favicon'),
        ),
    ]
