# Generated by Django 6.1.1 on 2026-09-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0016_club_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='is_visible',
            field=models.BooleanField(default=True, help_text='Se desmarcado, o clube ficará oculto para os usuários.', verbose_name='Visível no site'),
        ),
    ]
