# Generated by Django 6.1.1 on 2026-09-14 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0017_club_is_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='match_duration',
            field=models.IntegerField(default=90, help_text='Tempo padrão usado no calendário de agendamento. Ex: 90 para 1h30min.', verbose_name='Duração estimada por jogo (minutos)'),
        ),
    ]
