# Generated by Django 6.1.1 on 2026-09-16 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0018_tournament_match_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='card_image',
            field=models.ImageField(blank=True, help_text='Imagem de capa para o card na lista de clubes (se não preenchida, usa a Imagem de Fundo)', null=True, upload_to='clubs/cards/', verbose_name='Imagem do Card'),
        ),
    ]
