# Generated by Django 6.1.1 on 2026-09-16 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0019_club_card_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingtournament',
            options={'verbose_name': 'Torneio Sazonal', 'verbose_name_plural': 'Torneios Seasonais'},
        ),
    ]
