# Generated by Django 6.1.1 on 2026-09-16 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0020_alter_rankingtournament_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='use_points_by_round',
            field=models.BooleanField(default=False, verbose_name='Habilitar Pontuação por Fase/Avanço'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='use_points_by_set',
            field=models.BooleanField(default=True, verbose_name='Habilitar Pontuação por Resultado de Sets'),
        ),
    ]
