# Generated by Django 6.1.1 on 2026-09-17 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0021_tournament_use_points_by_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='is_knockout_court',
            field=models.BooleanField(default=False, verbose_name='Usada para Jogos de Torneios Eliminatórios?'),
        ),
    ]
