# Generated by Django 6.1.1 on 2026-09-17 03:40

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0022_court_is_knockout_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='competition_type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('simples', 'Simples'), ('duplas', 'Duplas')], default='simples', max_length=50, verbose_name='Competição'),
        ),
    ]
