# Generated by Django 6.1.1 on 2026-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0023_alter_tournament_competition_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='card_image_size',
            field=models.IntegerField(default=100, help_text='Ajuste o zoom da imagem no card.', verbose_name='Tamanho da Imagem do Card (%)'),
        ),
    ]
