# Generated by Django 6.1.1 on 2026-09-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0024_club_card_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='logo_size',
            field=models.IntegerField(default=100, help_text='Ajuste o tamanho do logo.', verbose_name='Tamanho do Logo (%)'),
        ),
    ]
