# Generated by Django 6.1.1 on 2026-09-18 21:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0025_club_logo_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='contact_whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp da Organização'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Sobre o Torneio (Regulamento, etc)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome do Local'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link de Como Chegar (Google Maps, etc)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_fee',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Taxa de Inscrição (Resumo)'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='whatsapp_group_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Grupo do Torneio'),
        ),
    ]
