# Generated by Django 6.1.1 on 2026-09-18 21:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0026_tournament_contact_whatsapp_tournament_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='registration_fee',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Taxa de Inscrição (Resumo)'),
        ),
    ]
