# Generated by Django 6.1.1 on 2026-09-18 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0027_alter_tournament_registration_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='registration_fee',
        ),
        migrations.AddField(
            model_name='tournament',
            name='fee_observation',
            field=models.TextField(blank=True, help_text='Ex: O código PIX para pagamento aparece na etapa de pagamento...', null=True, verbose_name='Observação sobre as Taxas (Rodapé)'),
        ),
        migrations.CreateModel(
            name='TournamentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome (Ex: Associado, Convidado)')),
                ('payment_method', models.CharField(default='Pagamento via PIX', max_length=100, verbose_name='Forma de Pagamento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor (R$)')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='clubs.tournament')),
            ],
            options={
                'verbose_name': 'Taxa de Inscrição',
                'verbose_name_plural': 'Taxas de Inscrição',
            },
        ),
    ]
