# Generated by Django 6.1.1 on 2026-09-18 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0028_remove_tournament_registration_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Data Limite de Inscrição'),
        ),
    ]
