# Generated by Django 6.1.1 on 2026-09-18 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0029_tournament_registration_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_players',
            field=models.IntegerField(blank=True, help_text='Deixe em branco para sem limite', null=True, verbose_name='Limite de Inscritos'),
        ),
    ]
