# Generated by Django 6.1.1 on 2026-09-18 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0030_category_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryplayer',
            name='fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clubs.tournamentfee', verbose_name='Taxa Escolhida'),
        ),
        migrations.AddField(
            model_name='categoryplayer',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente de Pagamento'), ('approved', 'Confirmada'), ('cancelled', 'Cancelada')], default='approved', max_length=20, verbose_name='Status do Pagamento'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='pix_code',
            field=models.TextField(blank=True, help_text='Código PIX para os atletas realizarem o pagamento da inscrição.', null=True, verbose_name='Código PIX (Copia e Cola)'),
        ),
    ]
