# Generated by Django 6.1.1 on 2026-09-18 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0031_categoryplayer_fee_categoryplayer_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='pix_code',
        ),
        migrations.AddField(
            model_name='tournamentfee',
            name='pix_code',
            field=models.TextField(blank=True, help_text='Código PIX Copia e Cola para este perfil/valor.', null=True, verbose_name='Código PIX Específico'),
        ),
    ]
