# Generated by Django 6.1.1 on 2026-09-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0032_remove_tournament_pix_code_tournamentfee_pix_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='use_site_registration',
            field=models.BooleanField(default=True, help_text='Se marcado, ativa o fluxo de inscrição em 3 etapas com pagamento no site. Se desmarcado, a inscrição é controlada externamente pelo ADM.', verbose_name='Usar inscrição pelo Site'),
        ),
    ]
