# Generated by Django 6.1.1 on 2026-09-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0033_tournament_use_site_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='use_limited_registrations',
            field=models.BooleanField(default=False, verbose_name='Usar inscrições limitadas?'),
        ),
        migrations.AlterField(
            model_name='category',
            name='max_players',
            field=models.IntegerField(blank=True, help_text='Válido se a opção acima estiver marcada', null=True, verbose_name='Limite de Inscritos'),
        ),
    ]
