# Generated by Django 6.1.1 on 2026-09-19 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0034_category_use_limited_registrations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryplayer',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pendente de Pagamento'), ('approved', 'Confirmada'), ('waitlist', 'Fila de Espera'), ('pending_waitlist', 'Pendente Fila de Espera'), ('cancelled', 'Cancelada')], default='approved', max_length=20, verbose_name='Status do Pagamento'),
        ),
    ]
