# Generated by Django 6.1.1 on 2026-09-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0035_alter_categoryplayer_payment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rankingtournament',
            options={'verbose_name': 'Torneio Sazonal', 'verbose_name_plural': 'Torneios Sazonais'},
        ),
    ]
