# Generated by Django 6.1.1 on 2026-09-20 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0036_alter_rankingtournament_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='has_departments',
            field=models.BooleanField(default=False, help_text='Marque se o clube organiza seus torneios e usuários em departamentos separados (Ex: Tênis, Beach Tennis).', verbose_name='Possui Departamentos?'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do Departamento')),
                ('image', models.ImageField(blank=True, null=True, upload_to='departments/cards/', verbose_name='Imagem/Card do Departamento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('administrators', models.ManyToManyField(blank=True, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='Administradores do Departamento')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='clubs.club', verbose_name='Clube')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.AddField(
            model_name='player',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Válido apenas se o clube utilizar departamentos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clubs.department', verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Obrigatório caso o clube use departamentos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='clubs.department', verbose_name='Departamento'),
        ),
    ]
