# Generated by Django 6.1.1 on 2026-09-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0037_club_has_departments_department_player_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image_size',
            field=models.IntegerField(default=100, help_text='Ajuste o zoom da imagem no card.', verbose_name='Tamanho da Imagem (%)'),
        ),
    ]
