# Generated by Django 6.1.1 on 2026-09-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0038_department_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='rules_pdf',
            field=models.FileField(blank=True, help_text='Upload do regulamento do departamento em formato PDF.', null=True, upload_to='departments/rules/', verbose_name='Regulamento (PDF)'),
        ),
        migrations.AlterField(
            model_name='club',
            name='rules_pdf',
            field=models.FileField(blank=True, help_text='Upload das regras gerais do clube em formato PDF.', null=True, upload_to='clubs/rules/', verbose_name='Regras Gerais do Clube (PDF)'),
        ),
    ]
