# Generated by Django 6.1.1 on 2026-09-22 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0039_department_rules_pdf_alter_club_rules_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='allow_visitors',
            field=models.BooleanField(default=True, help_text='Se marcado, qualquer pessoa pode visitar as páginas do clube sem login. Se desmarcado, apenas membros cadastrados podem visualizar.', verbose_name='Permitir Visitantes?'),
        ),
    ]
