# Generated by Django 6.1.1 on 2026-09-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0040_add_allow_visitors_to_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='message_for_athletes',
            field=models.CharField(blank=True, default='🎾 NÃO ESQUEÇAM DE COLOCAR NOS GRUPOS AS DATAS E HORÁRIOS DOS JOGOS, ASSIM COMO OS RESULTADOS 🎾', help_text='Aviso exibido no topo do torneio. Deixe em branco para não exibir.', max_length=255, null=True, verbose_name='Mensagem de Aviso aos Atletas'),
        ),
    ]
