# Generated by Django 6.1.1 on 2026-09-28 04:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0041_tournament_message_for_athletes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='message_for_athletes',
            field=ckeditor.fields.RichTextField(blank=True, default='🎾 NÃO ESQUEÇAM DE COLOCAR NOS GRUPOS AS DATAS E HORÁRIOS DOS JOGOS, ASSIM COMO OS RESULTADOS 🎾', help_text='Aviso exibido no topo do torneio. Deixe em branco para não exibir.', null=True, verbose_name='Mensagem de Aviso aos Atletas'),
        ),
    ]
