# Generated by Django 6.1.1 on 2026-09-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0042_alter_tournament_message_for_athletes'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryplayer',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Aceite'),
        ),
        migrations.AddField(
            model_name='categoryplayer',
            name='consent_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP do Aceite'),
        ),
        migrations.AddField(
            model_name='categoryplayer',
            name='terms_accepted',
            field=models.BooleanField(default=False, verbose_name='Termos Aceitos na Inscrição'),
        ),
        migrations.AddField(
            model_name='categoryplayer',
            name='terms_version',
            field=models.CharField(blank=True, max_length=50, verbose_name='Versão dos Termos'),
        ),
    ]
