# Generated by Django 6.1.1 on 2026-10-08 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0043_categoryplayer_consent_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='wo_a',
            field=models.BooleanField(default=False, verbose_name='WO'),
        ),
        migrations.AddField(
            model_name='match',
            name='wo_b',
            field=models.BooleanField(default=False, verbose_name='WO'),
        ),
    ]
